sudo: required

services: 
  - docker

before_install:
  - docker build -t fabi0brito/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run fabi0brito/react-test npm test -- --coverage

after_success: 
  - docker build -t fabi0brito/multi-client ./client
  - docker build -t fabi0brito/multi-nginx ./nginx
  - docker build -t fabi0brito/multi-server ./server
  - docker build -t fabi0brito/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push fabi0brito/multi-client
  - docker push fabi0brito/multi-nginx
  - docker push fabi0brito/multi-server
  - docker push fabi0brito/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-398599148408
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY